### PR TITLE
APF-679: Refactor project for common code

### PR DESCRIPTION
**Pull request by RyanBard**
* Rolled version to 2.0-SNAPSHOT
* Changed common to be common code for external use also (apf project)
* Changed comment-test to be common for ext use also (apf project)
* Added connectors-common-config for connector specific spring config
* Added connectors-common-test for connector specific test config
* Moved connectors into /connectors/samples
* Ported over some common code from APF
* Removed unused json files
* Removed unused ConnectorStatus class
* Added warning for invalid aws approval urls

Signed-off-by: John Bard <jbard@vmware.com>

### CODE REVIEW

**Comment by RyanBard** [comment]
I force pushed a logger.warning in while my other PR was closed. 
 Review this PR, but you can look at my comments explaining things in the original here: https://github.com/vmware/connectors-workspace-one/pull/10

**Comment by rworsnop** [comment]
The connectors directory was created so it would be immediately clear what was a connector and what was something else. Please put other stuff elsewhere.

**Comment by rworsnop** [comment]
While you're in there, so to speak, can you also add a javadoc exclusion for the github connector in the parent POM? I missed that when I reviewed the GH connector.

**Comment by RyanBard** [comment]
/connectors/samples isn't clear?

Just to make sure I understand, you're suggesting the following directories:

```
/common
/common-test
/connectors-common-config
/connectors-common-test
/connectors/jira
/connectors/salesforce
/connectors/servicenow
...
```

instead of:

```
/common
/common-test
/connectors/common-config
/connectors/common-test
/connectors/samples/jira
/connectors/samples/salesforce
/connectors/samples/servicenow
...
```

**Comment by rworsnop** [comment]
Ah, IDEA was confusing me by leaving the empty dirs under `connectors`. I'll come over.

**Pull request merged**
